version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "mysql"
    volumes:
      - ./dist:/app/dist
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: Wikimedia
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
